package controlador;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;
import modelo.Move;
import modelo.Pokemon;
import modelo.Trainer;

import java.io.IOException;
import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import crud.CargarEntrenador;
import crud.CargarTodosLosEntrenadores;
import funcionalidades.Batalla;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

public class BatallaControllerAntigua implements Initializable {

	@FXML
	private Button elegirMovimiento;
	@FXML
	private static Label muestraTurno;

	@FXML
	private Button seleccionar;
	@FXML
	private TableView tabla;
	@FXML
	private TableColumn mote;
	@FXML
	private TableColumn nombre;
	@FXML
	private TableColumn ataque;
	@FXML
	private TableColumn defensa;
	@FXML
	private TableColumn ataqueSp;
	@FXML
	private TableColumn defensaSp;
	@FXML
	private TableColumn velocidad;
	@FXML
	private TableColumn estamina;
	@FXML
	private TableColumn nivel;
	@FXML
	private TableColumn vitalidad;
	@FXML
	private TableColumn tipo1;
	@FXML
	private TableColumn tipo2;
	@FXML
	private Button atacar;


	



//	public static LinkedList<Pokemon> getEquipoJugador() {
//		return equipoJugador;
//	}
//
//	public void setEquipoJugador(LinkedList<Pokemon> equipoJugador) {
//		this.equipoJugador = equipoJugador;
//	}
//
//	private static int pokemonElegido = 0;
//
//	public static Pokemon getPokemonElegidoJugador() {
//		return pokemonElegidoJugador;
//	}
//
//	public static void setPokemonElegidoJugador(Pokemon pokemonElegidoObjeto) {
//		BatallaController.pokemonElegidoJugador = pokemonElegidoObjeto;
//	}
//
//	// probamos con un movimiento que creamos
//	private static Move movimietoJugador = null;
//	private Move movimietoMaquina = null;
//
//	public static Move getMovimietoJugador() {
//		return movimietoJugador;
//	}
//
//	public static void setMovimietoJugador(Move movimietoJugador) {
//		BatallaController.movimietoJugador = movimietoJugador;
//	}

	@FXML
	private Button cambiarPokemon;

	// Event Listener on Button[#cambiarPokemon].onAction
	@FXML
	public void cambiarPokemon(ActionEvent event) throws IOException {
		
//		movimietoJugador = null;
		
		
		// TODO Autogenerated
		// se abre la ventana con los pokemon del jugador para que seleccione otro
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/ElegirPokemonBatalla.fxml"));

		Parent root = loader.load();

		Scene scene = new Scene(root);

		Stage stage = new Stage();
//				stage.initModality(Modality.APPLICATION_MODAL); (hace que la ventana sea modal)

		stage.setScene(scene);
		stage.show();

	}

	// Event Listener on Button[#elegirMovimiento].onAction
	@FXML
	public void elegirMovimiento(ActionEvent event) throws IOException {
		// TODO Autogenerated
		// se abre la ventana con los pokemon del jugador para que seleccione otro
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/ElegirMovimientos.fxml"));

		Parent root = loader.load();

		Scene scene = new Scene(root);

		Stage stage = new Stage();
//				stage.initModality(Modality.APPLICATION_MODAL); (hace que la ventana sea modal)

		stage.setScene(scene);
		stage.show();

	}

	// Event Listener on Button[#atacar].onAction
	@FXML
	public void atacar(ActionEvent event) throws IOException {
		// TODO Autogenerated


			

			



	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

	}

}
