package controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import cargar.CargarPokemon;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import modelo.CapturaMedianteLinkedlist;
import modelo.Pokemon;

public class CapturaController2 implements Initializable{
	@FXML
	private Button capturarPokemon;
	@FXML
	private Button bucarPokemon;
	@FXML
	private Label pokemonEncontrado;
	@FXML
	private Label pokemonCapturado;

	// Event Listener on Button[#capturarPokemon].onAction
	@FXML
	public void capturarPokemon(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bucarPokemon].onAction
	@FXML
	public void bucarPokemon(ActionEvent event) throws IOException {
		// TODO Autogenerated
	
		

		
		
		Pokemon pokemonEcontrado=CapturaMedianteLinkedlist.mostrarPokemonEncontrado();
		
		
		
		pokemonEncontrado.setText(pokemonEcontrado.getName());
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		LinkedList<Pokemon> pokemon=CargarPokemon.cargarPokemonDesdeBbDd();
		
//		for (int i = 0; i < pokemon.size(); i++) {
//            System.out.println(pokemon.get(i).toString());
//		}
//		
	}
}
