package controlador;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import cargar.CargarEntrenador;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import modelo.GeneraPokemonAleatorio;
import modelo.Pokemon;
import modelo.Trainer;

public class CapturaController implements Initializable {
	@FXML
	private Button capturarPokemon;
	@FXML
	private Button bucarPokemon;
	@FXML
	private Label pokemonEncontrado;
	@FXML
	private Label pokemonCapturado;



	private static Pokemon pokemon;

	private Trainer entrenador = CargarEntrenador.getEntrenador();

	

	@FXML
	private Button btnInsertarMote;
	@FXML
	private TextField txtMote;

	public Pokemon getPokemon() {
		return pokemon;
	}

	// Event Listener on Button[#btnInsertarMote].onAction
	@FXML
	public void insertarMotre(ActionEvent event) {
		// TODO Autogenerated
		
		String mote=txtMote.getText();

		entrenador.insertarEnBbDdElPokemonEncontrado(pokemon,mote);
	
		
//		pokemonCapturado.setText("Enhorabuenas has capturado un nuevo " + pokemon.getName());
		
		 Stage stage = (Stage) this.txtMote.getScene().getWindow();
	     stage.close();
	}

	// Event Listener on Button[#capturarPokemon].onAction
	@FXML
	public void capturarPokemon(ActionEvent event) throws IOException {

		if (pokemon != null) {


		
		
			
			
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/InsertarMote.fxml"));

			Parent root = loader.load();

			Scene scene = new Scene(root);

			Stage stage = new Stage();
//			stage.initModality(Modality.APPLICATION_MODAL); (hace que la ventana sea modal)

			stage.setScene(scene);
			stage.show();

		}

		else if (pokemon == null)
			pokemonEncontrado.setText("Aún no has encontrado ningun pokemon");
	}

	// Event Listener on Button[#bucarPokemon].onAction
	@FXML
	public void bucarPokemon(ActionEvent event) {

		pokemon = GeneraPokemonAleatorio.mostrarPokemonEncontrado();

		pokemonEncontrado.setText("has enconrado un " + pokemon.getName());
		
		
//		InsertarMoteController.setPokemon(pokemon);

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
//		CargarPokemon.cargarPokemonDesdeBbDd();

//		for (int i = 0; i < pokemon.size(); i++) {
//            System.out.println(pokemon.get(i).toString());
//		}
//		
	}
}
