package controlador;

import javafx.fxml.FXML;


import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import modelo.CrearUsuarioNuevo;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class CrearUsuarioController {
	@FXML
	private TextField txtUsuario;
	@FXML
	private Label lblUsuarioDenegado;
	@FXML
	private Button btnCrearUsuario;
	
	@FXML
	public void mostrarLblEnBlanco(MouseEvent event) {
		// TODO Autogenerated
		lblUsuarioDenegado.setText("");
	}

	// Event Listener on Button[#btnCrearUsuario].onAction
	@FXML
	public void crearUsuario(MouseEvent event) {
		// TODO Autogenerated
		
		String nombreNuevo=txtUsuario.getText();
		
		if(CrearUsuarioNuevo.crearUsuarioNuevo(nombreNuevo)) {
			
			 Stage stage = (Stage) this.btnCrearUsuario.getScene().getWindow();
		     stage.close();
		}
			
		
		else lblUsuarioDenegado.setText("Nombre de usuario no permitido");
	}
}
