package controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import modelo.Pokemon;
import modelo.Trainer;

import java.io.IOException;
import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import cargar.CargarEntrenador;
import funcionalidades.Entrenar;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class EntrenarController implements Initializable {
	@FXML
	private Button btnEntrenarPokemon;
	@FXML
	private Label lblDescripcion;
	@FXML
	private Label lblEntrenamiento;
	@FXML
	private Label lblPokemonAEntrenar;
	@FXML
	private TextField txtPokemonAEntrenar;
	@FXML
	private TextField txtTipoDeEntrenamiento;

	private Pokemon pokemonSeleccionado;

	private Trainer entrenador = CargarEntrenador.getEntrenador();

	private LinkedList<Pokemon> pokemonsEntrenador = entrenador.getTodosLosPokemon();

	// Event Listener on Button[#btnEntrenarPokemon].onAction
	@FXML
	public void entrenamiento(ActionEvent event) {
		// TODO Autogenerated

		String moteDelPokemonEntrenamos = txtPokemonAEntrenar.getText();
		String entrenaminetoElegido = txtTipoDeEntrenamiento.getText();

		try {
			Entrenar.entrenar(entrenador, moteDelPokemonEntrenamos, entrenaminetoElegido);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			txtTipoDeEntrenamiento.setText("El entrenamiento no existe");
		} catch (NullPointerException e) {
			// TODO Auto-generated catch block
			txtPokemonAEntrenar.setText("El pokemon no existe");
		}

//		System.out.println(pokemonsEntrenador.get(0).toString());

//	System.out.println(pokemonSeleccionado.toString());

		System.out.println(entrenador.getPokeDollar());

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

		System.out.println(entrenador.toString());
//		System.out.println(pokemonsEntrenador.toString());

	}
}
