package controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

import java.net.URL;
import java.util.LinkedList;
import java.util.ResourceBundle;

import crud.CargarEntrenador;
import funcionalidades.InsertarEnEquipo2;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import modelo.Pokemon;
import modelo.Trainer;
import modelo.Types;
import javafx.scene.control.TableColumn;

public class InsertarEnEquio2Controller implements Initializable {
	@FXML
	 private Label lblEquipoComplero;
	@FXML
	private Button quitar;
	@FXML
	private Button seleccionar;
	@FXML
	private TableView tablaEquipo;
	@FXML
	private TableColumn moteEquipo;
	@FXML
	private TableColumn nombreEquipo;
	@FXML
	private TableColumn ataqueEquipo;
	@FXML
	private TableColumn defensaEquipo;
	@FXML
	private TableColumn ataqueSpEquipo;
	@FXML
	private TableColumn defensaSpEquipo;
	@FXML
	private TableColumn velocidadEquipo;
	@FXML
	private TableColumn estaminaEquipo;
	@FXML
	private TableColumn nivelEquipo;
	@FXML
	private TableColumn vitalidadEquipo;
	@FXML
	private TableColumn tipo1Equipo;
	@FXML
	private TableColumn tipo2Equipo;
	@FXML
	private TableView tabla;
	@FXML
	private TableColumn mote;
	@FXML
	private TableColumn nombre;
	@FXML
	private TableColumn ataque;
	@FXML
	private TableColumn defensa;
	@FXML
	private TableColumn ataqueSp;
	@FXML
	private TableColumn defensaSp;
	@FXML
	private TableColumn velocidad;
	@FXML
	private TableColumn estamina;
	@FXML
	private TableColumn nivel;
	@FXML
	private TableColumn vitalidad;
	@FXML
	private TableColumn tipo1;
	@FXML
	private TableColumn tipo2;

	private Trainer entrenador = CargarEntrenador.getEntrenador();

	private LinkedList<Pokemon> todosLosPokemon;

	private LinkedList<Pokemon> equipoPokemon;

	// añadimos a la ObservableList todos los pokemon que posee el entrenador
	public ObservableList<Pokemon> muestraTodoLosPokemon() {

		entrenador = CargarEntrenador.getEntrenador();

		todosLosPokemon = entrenador.getTodosLosPokemon();

		ObservableList<Pokemon> lista = FXCollections.observableArrayList();

		for (int i = 0; i < todosLosPokemon.size(); i++) {

			lista.add(todosLosPokemon.get(i));

		}
		return lista;
	}

	public ObservableList<Pokemon> muestraEquipo() {

		entrenador = CargarEntrenador.getEntrenador();

		equipoPokemon = entrenador.getEquipoPokemon();

		ObservableList<Pokemon> lista = FXCollections.observableArrayList();

		for (int i = 0; i < equipoPokemon.size(); i++) {

			lista.add(equipoPokemon.get(i));

		}
		return lista;
	}

	// Event Listener on Button[#quitar].onAction
	@FXML
	public void quitar(ActionEvent event) {
		// TODO Autogenerated
		
		try {
			ObservableList<Pokemon> pokemonSeleccionado = tablaEquipo.getSelectionModel().getSelectedItems();

			int idPokemonSeleccionado = pokemonSeleccionado.get(0).getId();

//			InsertarEnEquipo2.sacarDeEquipo(idPokemonSeleccionado, entrenador);
			
			InsertarEnEquipo2.sacarDeEquipo2(pokemonSeleccionado.get(0), entrenador);

			tabla.setItems(muestraTodoLosPokemon());

			tablaEquipo.setItems(muestraEquipo());
			
		} catch (Exception e) {
			// TODO: handle exception
			
			lblEquipoComplero.setText("EQUIPO VACIO");
		}

	

	}

	// Event Listener on Button[#seleccionar].onAction
	@FXML
	public void seleccionar(ActionEvent event) {
		// TODO Autogenerated
		
		if(entrenador.getEquipoPokemon().size()<6) {
			ObservableList<Pokemon> pokemonSeleccionado = tabla.getSelectionModel().getSelectedItems();

//			tablaEquipo.getItems().add(pokemonSeleccionado.get(0));
	//
			int idPokemonSeleccionado = pokemonSeleccionado.get(0).getId();
	//
//			tabla.getItems().remove(pokemonSeleccionado.get(0));

			InsertarEnEquipo2.inserarEnEquipo(idPokemonSeleccionado, entrenador);

			tabla.setItems(muestraTodoLosPokemon());

			tablaEquipo.setItems(muestraEquipo());
			
			lblEquipoComplero.setText("");
			
		}else lblEquipoComplero.setText("EQUIPO COMPLETO\nSACA UNO PRIMERO");

		
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

		tabla.setItems(muestraTodoLosPokemon());

		tablaEquipo.setItems(muestraEquipo());

//		tabla.getColumns().addAll(c1);

		moteEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("nickname"));
		nombreEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("name"));
		ataqueEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("atk"));
		defensaEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("def"));
		ataqueSpEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("spAtk"));
		defensaSpEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("spDef"));
		vitalidadEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("vit"));
		velocidadEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("speed"));
		estaminaEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("stamina"));
		nivelEquipo.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("level"));
		
		
		

		mote.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("nickname"));
		nombre.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("name"));
		ataque.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("atk"));
		defensa.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("def"));
		ataqueSp.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("spAtk"));
		defensaSp.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("spDef"));
		vitalidad.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("vit"));
		velocidad.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("speed"));
		estamina.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("stamina"));
		nivel.setCellValueFactory(new PropertyValueFactory<Pokemon, String>("level"));


	}
}
