package controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import modelo.Pokemon;
import modelo.Trainer;

import java.lang.reflect.Array;
import java.net.URL;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.ResourceBundle;

import cargar.CargarEntrenador;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class InsertarEnEquipoController implements Initializable {
	@FXML
	private TextField txtInsertar;
	@FXML
	private TextField txtSacar;
	@FXML
	private Button btnInsertar;
	@FXML
	private Label lblInsertar;
	@FXML
	private Label lblSacar;
	@FXML
	private Label lblEquipo;
	@FXML
	private Label lblTodos;

	private Trainer entrenador = CargarEntrenador.getEntrenador();

	// Event Listener on Button[#btnInsertar].onAction
	@FXML
	public void insertar(ActionEvent event) {
		// TODO Autogenerated

		try {
			String mote = txtInsertar.getText();
			
			int posicion=-1;

//			int idPokemonSacar=Integer.parseInt(lblSacar.getText());

			if (entrenador.getEquipoPokemon().size() < 6) {
				
				for(int i=0;i<entrenador.getTodosLosPokemon().size();i++) {
					
					if(entrenador.getTodosLosPokemon().get(i).getNickname().equalsIgnoreCase(mote))posicion=i;
					
				}
				if(posicion!=-1) {
					Pokemon insertar = entrenador.getTodosLosPokemon().get(posicion);

					entrenador.getEquipoPokemon().add(insertar);

					entrenador.getTodosLosPokemon().remove(insertar);


					lblTodos.setText(entrenador.getTodosLosPokemon().toString());

					lblEquipo.setText(entrenador.getEquipoPokemon().toString());	
				}else 

					lblEquipo.setText("mote inexistente\n" + entrenador.getEquipoPokemon().toString());

			} else

				lblEquipo.setText("Saca uno para poder insertar otro\n" + entrenador.getEquipoPokemon().toString());

		} catch (Exception e) {
			// TODO: handle exception
			lblEquipo.setText("Valor incorrecto\n" + entrenador.getEquipoPokemon().toString());
		}

//		Pokemon sacar=entrenador.getEquipoPokemon().get(idPokemonSacar);

//		LinkedList<Pokemon>insertarPokemonEnEquipo=entrenador.getEquipoPokemon();
//		insertarPokemonEnEquipo.add(insertar);
//		
//		entrenador.setEquipoPokemon(insertarPokemonEnEquipo);
//		
//		System.out.println(insertarPokemonEnEquipo.toString());

//		entrenador.getTodosLosPokemon().remove(insertar);

//		(idPokemonInsertar);

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub

		String todosPokemon = entrenador.getTodosLosPokemon().toString();

		String equipo = entrenador.getEquipoPokemon().toString();

		lblTodos.setText(todosPokemon);

		lblEquipo.setText(equipo);

	}
}
