package controlador;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.stage.Stage;

public class PruebaController {
	@FXML
	private Button btnBuscar;
	@FXML
	private Button btnCapturar;
	@FXML
	private Label lblMuestraPokemon;

	// Event Listener on Button[#btnBuscar].onAction
	@FXML
	public void buscar(ActionEvent event) {
		// TODO Autogenerated
		
		lblMuestraPokemon.setText("hola");
		
	}
	// Event Listener on Button[#btnCapturar].onAction
	@FXML
	public void capturar(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		// abrir la siguiente ventana
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/ElegirAccion.fxml"));

		Parent root = loader.load();

		Scene scene = new Scene(root);

		Stage stage = new Stage();

		stage.setScene(scene);
		stage.show();
		// se cierra la ventana actual
//		Stage stage2 = (Stage) this.btnCapturar.getScene().getWindow();
//		stage2.close();
		
	}
}
