package controlador;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.stage.Stage;

public class ResultadoCombateController implements Initializable{
	@FXML
	private Label lblResultado;
	@FXML
	private Button btnAceptar;
	@FXML
	private ImageView imgResultado;

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
		
		// se cierra la ventana actual
		Stage stage2 = (Stage) this.lblResultado.getScene().getWindow();
		stage2.close();
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
		lblResultado.setText(BatallaController.resultado);
		
		imgResultado.setImage(BatallaController.imagenResultado);
		
		
	}
}
