package controlador;

import javafx.fxml.FXML;

import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.MouseEvent;
import javafx.stage.Modality;
import javafx.stage.Stage;
import modelo.Trainer;

import java.io.IOException;

import cargar.CargarEntrenador;

import cargar.CargarPokemons;
import javafx.event.ActionEvent;

public class SeleccionarJugadorController2 {
	@FXML
	private TextField TxtInsertarJugador;
	@FXML
	private Button btbcargarEntrenador;

	@FXML
	private Label lblMostrarUsuario;
	
	
	@FXML
	private Button btbCrearUsuario;
	
	
	// Event Listener on Button[#btbCrearUsuario].onAction
	@FXML
	public void crearUsuario(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/CrearUsuario.fxml"));

		Parent root = loader.load();

		Scene scene = new Scene(root);

		Stage stage = new Stage();
		stage.initModality(Modality.APPLICATION_MODAL); //(hace que la ventana sea modal)

		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#btbcargarEntrenador].onMousePressed
	@FXML
	public void mostrarLblEnBlanco(MouseEvent event) {
		// TODO Autogenerated
	

		lblMostrarUsuario.setText("");
	}



	// Event Listener on Button[#btbcargarEntrenador].onMouseReleased
	@FXML
	public void cargarEntrenador(MouseEvent event) throws IOException {
		// TODO Autogenerated

		String entrenador = TxtInsertarJugador.getText().toUpperCase();

		try {
			CargarEntrenador.cargarEntrenador(entrenador);

			System.out.println(CargarEntrenador.getEntrenador().toString());

			CargarPokemons.cargarPokemonDesdeBbDd();
			
			//abrir la siguiente ventana
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/ElegirAccion.fxml"));

			Parent root = loader.load();

			Scene scene = new Scene(root);

			Stage stage = new Stage();
//			stage.initModality(Modality.APPLICATION_MODAL); (hace que la ventana sea modal)

			stage.setScene(scene);
			stage.show();
		//se cierra la ventana actual	
			 Stage stage2 = (Stage) this.TxtInsertarJugador.getScene().getWindow();
		     stage2.close();

		} catch (IOException e) {
			// TODO Auto-generated catch block
//			e.printStackTrace();

			lblMostrarUsuario.setText("Usuario desconocido");
		}


	}
}
