package controlador;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class TiendaController {
	@FXML
	private TableView tienda;
	@FXML
	private TableColumn objeto;
	@FXML
	private TableColumn ataque;
	@FXML
	private TableColumn defensa;
	@FXML
	private TableColumn ataqueSp;
	@FXML
	private TableColumn defensaSp;
	@FXML
	private TableColumn velocidad;
	@FXML
	private TableColumn estamina;
	@FXML
	private TableColumn precio;
	@FXML
	private TableView mochila;
	@FXML
	private TableColumn objetosEntrenador;
	@FXML
	private TableColumn cantidadObjetos;
	@FXML
	private TableView Pokemon;
	@FXML
	private TableColumn motePokemon;
	@FXML
	private TableColumn nombrePokemon;
	@FXML
	private TableColumn ataquePokemon;
	@FXML
	private TableColumn defensaPokemon;
	@FXML
	private TableColumn ataqueSpPokemon;
	@FXML
	private TableColumn defensaSpPokemon;
	@FXML
	private TableColumn velocidadPokemon;
	@FXML
	private TableColumn estaminaPokemon;
	@FXML
	private Button comprar;
	@FXML
	private Button quitar;
	@FXML
	private Button vender;
	@FXML
	private Button insertar;
	@FXML
	private Label pokedollarEntrenador;

	// Event Listener on Button[#comprar].onAction
	@FXML
	public void comprar(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#quitar].onAction
	@FXML
	public void quitar(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#vender].onAction
	@FXML
	public void vender(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#insertar].onAction
	@FXML
	public void insertar(ActionEvent event) {
		// TODO Autogenerated
	}
}
