package vista;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class Entrenar2Controller {
	@FXML
	private Label pokedollarEntrenador;
	@FXML
	private TableView tabla;
	@FXML
	private TableColumn moteEquipo;
	@FXML
	private TableColumn nombreEquipo;
	@FXML
	private TableColumn ataqueEquipo;
	@FXML
	private TableColumn defensaEquipo;
	@FXML
	private TableColumn ataqueSpEquipo;
	@FXML
	private TableColumn defensaSpEquipo;
	@FXML
	private TableColumn velocidadEquipo;
	@FXML
	private TableColumn estaminaEquipo;
	@FXML
	private TableColumn nivelEquipo;
	@FXML
	private TableColumn vitalidadEquipo;
	@FXML
	private Label precioEntrenamiento;

	// Event Listener on Button.onAction
	@FXML
	public void furioso(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void funcional(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseEntered
	@FXML
	public void precioFuncional(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void onirico(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void pesado(ActionEvent event) {
		// TODO Autogenerated
	}
}
