package vista;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.ChoiceBox;

public class InsertarEnEquipoController {
	@FXML
	private ChoiceBox caja;

	// Event Listener on ChoiceBox[#caja].onDragDetected
	@FXML
	public void nombreSeleccionado(MouseEvent event) {
		// TODO Autogenerated
	}
}
