package vista;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import pokemon.ModeloBatalla;
import pokemon.Pokemon;

public class LuchaController {
	@FXML
	private Button pegar;
	@FXML
	private Button salir;
	@FXML
	private Label label;

	@FXML
	private Label label2;

	Pokemon pokemon1 = new Pokemon();
	Pokemon pokemon2 = new Pokemon();
	
	int contador1=0;
	int contador2=0;

	// Event Listener on Button[#pegar].onAction
	@FXML
	public void pegar(ActionEvent event) {
		// TODO Autogenerated

		int vida = pokemon2.getVit();

//		int power=ModeloBatalla.realizaAtaque("1");

		int power = 0;
		try {

			Connection miCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/curso_sql", "root", "");

			String sentecia = "SELECT * FROM MOVE where id=?";
			PreparedStatement miPSt = miCon.prepareStatement(sentecia);
			miPSt.setString(1, "1");

			ResultSet miRs = miPSt.executeQuery();

			while (miRs.next()) {

				power = Integer.parseInt(miRs.getString(3));

			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		int vidaActual = vida - power;

		pokemon2.setVit(vidaActual);

		label.setText("El oponente tiene " + vidaActual + " putos de vida");

		int valor = (int) (Math.random() * 10);

		int vida2 = pokemon1.getVit();

		int vidaActual2 = vida2 - valor;
		
		pokemon1.setVit(vidaActual2);

		label.setText("El oponente tiene " + vidaActual + " putos de vida" +
		"\n"+valor+ "\ntu pokemon tiene " + vidaActual2
				+ " putos de vida");

		if (pokemon1.getVit() == 0) {
			label2.setText("El pokemon1 ha muerto");
			
			contador1++;
			
		}
			
		if (pokemon2.getVit() == 0) {
			label2.setText("El pokemon2 ha muerto");
			pokemon2 = new Pokemon();
			contador2++;
		}
		
		if(contador2>1)label.setText("has ganado la batalla");
	}

	// Event Listener on Button[#salir].onAction
	@FXML
	public void salir(ActionEvent event) {
		// TODO Autogenerated
	}
}
