//package vista;
//
//import javafx.fxml.FXML;
//import javafx.fxml.FXMLLoader;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
//import javafx.scene.control.Button;
//
//import java.io.IOException;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//
//import javafx.event.ActionEvent;
//
//import javafx.scene.control.Label;
//import javafx.stage.Stage;
//
//import pokemon.EscenaPrincipalController;
//import pokemon.ModeloBatalla;
//import pokemon.Pokemon;
//
//public class LuchaController {
//	@FXML
//	private Button pegar;
//	@FXML
//	private Button salir;
//	@FXML
//	private Label label;
//
//	@FXML
//	private Label label2;
//	
//	private String nombre;
//
//	public String getNombre() {
//		return nombre;
//	}
//
//	public void setNombre(String nombre) {
//		this.nombre = nombre;
//	}
//
//	Pokemon pokemon1 = new Pokemon("a");
//	Pokemon pokemon2 = new Pokemon("a");
//	
//	int contador1=0;
//	int contador2=0;
//
//	// Event Listener on Button[#pegar].onAction
//	@FXML
//	public void pegar(ActionEvent event)throws IOException {
//		
//	
//		
//		
//		
//		int vida = pokemon2.getVit();
//
////		int power=ModeloBatalla.realizaAtaque("1");
//
//		int power = 0;
//		try {
//
//			Connection miCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/curso_sql", "root", "");
//
//			String sentecia = "SELECT * FROM MOVE where id=?";
//			PreparedStatement miPSt = miCon.prepareStatement(sentecia);
//			miPSt.setString(1, "1");
//
//			ResultSet miRs = miPSt.executeQuery();
//
//			while (miRs.next()) {
//
//				power = Integer.parseInt(miRs.getString(3));
//
//			}
//
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//
//		int vidaActual = vida - power;
//
//		pokemon2.setVit(vidaActual);
//
//		label.setText("El oponente tiene " + vidaActual + " putos de vida");
//
//		int valor = (int) (Math.random() * 10);
//
//		int vida2 = pokemon1.getVit();
//
//		int vidaActual2 = vida2 - valor;
//		
//		pokemon1.setVit(vidaActual2);
//
//		label.setText("El oponente tiene " + vidaActual + " putos de vida" +
//		"\n"+valor+ "\ntu pokemon tiene " + vidaActual2
//				+ " putos de vida");
//
//		if (pokemon1.getVit() == 0) {
//			label2.setText("El pokemon1 ha muerto");
//			
//			contador1++;
//			
//		}
//			
//		if (pokemon2.getVit() == 0) {
//			label2.setText("El pokemon2 ha muerto");
//			pokemon2 = new Pokemon();
//			contador2++;
//		}
//		//si deja a cero la vida del oponente dos veces, o lo que es lo mismo ha matado a dos pokemon, gana la batalla
//		if(contador2>=2) {
//			label.setText("has ganado la batalla");
//			
//			nombre="Has ganado la batalla";
//			
//			FXMLLoader loader = new FXMLLoader(getClass().getResource("EscenaPrincipal.fxml"));
//
//			Parent root = loader.load();
//			
//			EscenaPrincipalController controlador=loader.getController();
//			
//			controlador.setName(nombre);
//			
//			System.out.println(nombre);
//			
//			Scene scene = new Scene(root);
//
//			Stage stage2 = new Stage();
//
//			
//			stage2.setScene(scene);
//			stage2.showAndWait();
//			
//		}
//	}
//
//	// Event Listener on Button[#salir].onAction
//	@FXML
//	public void salir(ActionEvent event) {
//		// TODO Autogenerated
//		
//		
//	}
//}
