package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class LoginController {
	@FXML
	private TextField txtfUser;
	@FXML
	private Label lblUser;
	@FXML
	private Button btnCheckUser;
	@FXML
	private TextField txtfPass;
	@FXML
	private Label lblPass;
	
	

	// Event Listener on Button[#btnCheckUser].onAction
	@FXML
	public void checkUser(ActionEvent event) {
		// TODO Autogenerated
	}
}
