package pokemon;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class EscenaPrincipal2Controller {
	@FXML
	private Button botonAtaquePatada;

	// Event Listener on Button[#botonAtaquePatada].onAction
	@FXML
	public void patada(ActionEvent event) {
		// TODO Autogenerated
	}
}
