package pokemon;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class EscenaPrincipalController {
	@FXML
	private Button btnabrir;
	@FXML
	private TextField resultado;
	@FXML
	private Label label1;

	// Event Listener on Button[#btnabrir].onAction
	@FXML
	public void abrir(ActionEvent event)throws IOException {
		// TODO Autogenerated
		

		 //cierra la ventana en la que estamos actualmente (ventana insertar nickname del jugador)
		    Node source = (Node) event.getSource();
		    Stage stage = (Stage) source.getScene().getWindow();
		    stage.close();
		
		
	//abre una nueva ventanda(ventana elegir accion que queremos realizar: cazar, pelear,etc)
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/EscenaPrincipal2.fxml"));

		Parent root = loader.load();

		Scene scene = new Scene(root);

		Stage stage2 = new Stage();


		stage2.setScene(scene);
		stage2.show();

	}
}
