package pokemon;

import javafx.fxml.FXML;
 
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import cargar.CargarEntrenador;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class EscenaPrincipalController {
	@FXML
	private Button btnabrir;
	@FXML
	public  TextField resultado;
	@FXML
	private Label label1;
	
	private String name="";
	

	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	// Event Listener on Button[#btnabrir].onAction
	@FXML
	public void abrir(ActionEvent event)throws IOException {
		// TODO Autogenerated
		
		
		
		
		
		
//	
//		
//
//		    Node source = (Node) event.getSource();
//		    Stage stage = (Stage) source.getScene().getWindow();
//		    stage.close();
//		
//
//		FXMLLoader loader = new FXMLLoader(getClass().getResource("vista/prueba.fxml"));
//
//		Parent root = loader.load();
//		
//		pruebaController controlador=loader.getController();
//
//
//		Scene scene = new Scene(root);
//
//		Stage stage1 = new Stage();
//
//		
//		stage1.setScene(scene);
//		stage1.showAndWait();
//	
		

		
		
	}
}
