package pokemon;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class EscenaPrincipal2Controller {
	@FXML
	private Button botonAtaquePatada;
	@FXML
	private Label lbCargarEntrenador;

	String nombre;

	public String getNombre() {
		return nombre;
	}

	

	// Event Listener on Button[#botonAtaquePatada].onAction
	@FXML
	public void patada(ActionEvent event)throws IOException {
		// TODO Autogenerated
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/vista/Lucha.fxml"));

		Parent root = loader.load();
		
	
		
	

		Scene scene = new Scene(root);

		Stage stage2 = new Stage();

		
		stage2.setScene(scene);
		stage2.showAndWait();
		
	}
}
