package modelo;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.Scanner;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class EscenaPrincipalController {
	@FXML
	private Button botonPatada;
	@FXML
	private TextField resultado;
	@FXML
	private Label label1;

	// Event Listener on Button[#botonPatada].onAction
	@FXML
	static Scanner sc;
	

	public static int patada(ActionEvent event) {
		// TODO Autogenerated
		
		
		
//		sc.close();
		
		return 0;
	}
}
